package mate.academy.service;

import java.math.BigDecimal;
import java.util.List;

import lombok.extern.slf4j.Slf4j;
import mate.academy.model.Order;
import mate.academy.model.Product;

@Slf4j
public class OrderServiceImpl implements OrderService {
    @Override
    public Order completeOrder(Long userId) {

        log.info("Method completeOrder was called with userId = {}", userId);
        List<Product> products = getAllProductsFromShoppingCart(userId);
        Order order = new Order(products, userId);
        // NOTE: In production ready code this order identifier should be generated by DB
        // For test purpose we simplify this and return dummy data
        order.setOrderId(1L);
        return order;
    }

    private List<Product> getAllProductsFromShoppingCart(Long userId) {
        // NOTE: In production ready code this method should fetch data from DB
        // For test purpose we simplify this method and return dummy data
        Product iphone = new Product("iPhone X", BigDecimal.valueOf(1199));
        Product macBook = new Product("MacBook Air 2020", BigDecimal.valueOf(1399));
        Product xiaomi = new Product("Xiaomi 12", BigDecimal.valueOf(499));
        List<Product> products = List.of(iphone, macBook, xiaomi);

        log.debug("Data was successfully fetched from DB: {}", products);
        return products;
    }
}
